### ISSUE TITLE
Blocks with inline equation gets deleted when focused

### ISSUE THREAD

**Issue by DhruvaSambrani** [toeverything/AFFiNE#10208]
### What happened?

Blocks with inline equation gets deleted when focused. See video

https://github.com/user-attachments/assets/3e27a82b-abcd-4800-b53a-f5d2ae7f3dd6

### Distribution version

Linux

### Are you self-hosting?

- [x] Yes

### Anything else?

**NOTE: This is on Affine Canary, Affine Stable is ok**

**Comment by DhruvaSambrani** [comment]
- Focus does not return to editor when the equation pop up is closed. An additional mouseclick is necessary
- the error does not occur if focus is returned by mouse click to the same block, and then something is typed.

From these two observations, it seems as if inline equation finalization doesn't work as well as expected

**Comment by Flrande** [comment]
https://github.com/toeverything/AFFiNE/pull/10309

This PR should fix it. Welcome to continue feedback.

**Comment by DhruvaSambrani** [comment]
@Flrande on 0.20.0_canary.13 issue still persists ~with same behaviour as before~

![Image](https://github.com/user-attachments/assets/7cd49f4b-db4a-49e9-a189-bfd17ea81661)

edit:
no, the issue only persists on documents created before the fix applied. New docs are ok. Odd bug, but ya

**Comment by batchor** [comment]
The lesson I learned, and I hope other users can learn from as well, is to avoid any "open-source" project where at least one developer has a single Chinese character in their profile.

https://github.com/toeverything/AFFiNE/issues/6641
https://github.com/toeverything/AFFiNE/issues/8537
https://github.com/toeverything/AFFiNE/discussions/6646
https://github.com/toeverything/AFFiNE/issues/7227

**Comment by DhruvaSambrani** [comment]
@Flrande any ideas how i can fix this?

**Comment by Flrande** [comment]
> [@Flrande](https://github.com/Flrande) any ideas how i can fix this?

Sorry for the late reply. Could you provide the reproduction video and the version?

**Comment by Flrande** [comment]
I think I reproduced it. I will fix it later.

**Comment by DhruvaSambrani** [comment]
Current workaround is to duplicate the files and delete the original. It works if few, but otherwise 💀
