### ISSUE TITLE
​Desktop version crashes. Version 20.4 does not work !

### ISSUE THREAD

**Issue by valeri63mart** [toeverything/AFFiNE#10536]
### What happened?

I was actively working on the page, it began to work with delays, and after freezing it stopped opening.
The top-level page sync is continuously trying to sync.

![Image](https://github.com/user-attachments/assets/b9b1fc2b-589b-496c-b5d0-2570743228bd)
Of all the pages, only one subordinate page is opened. 
I deleted the application and installed it again, logged out and logged into my account, all this did not help.
Everything works in the web version and thank God my work was preserved.

### Distribution version

Windows x64

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Are you self-hosting?

- [ ] Yes

### Relevant log output

```shell

```

**Comment by forehalo** [comment]
should be fixed in 0.20.3, please upgrade to the latest version.

**Comment by valeri63mart** [comment]
> should be fixed in 0.20.3, please upgrade to the latest version.

Good afternoon.
This all happens already in version 20.3

![Image](https://github.com/user-attachments/assets/c6d40562-f100-4926-bc5e-1718601ecdd7)

**Comment by valeri63mart** [comment]
Today I reinstalled version 20.4, but the problem remains, it seems like I’m tripping on one page somewhere, it’s impossible to work on the desktop version.
![Image](https://github.com/user-attachments/assets/4d4f48cd-1ef6-46f7-997c-b82dfa30fdef)

**Comment by forehalo** [comment]
please reach us through support@toeverything.info and provide us your account email, we will help you diagnose the sync logic
