### ISSUE TITLE
Unhandle Runtime error `Error: yText must be attached to a Y.Doc`

### ISSUE THREAD

**Issue by Zheaoli** [toeverything/AFFiNE#1261]
![image](https://user-images.githubusercontent.com/7054676/222408322-b9abf87f-9e62-45de-ac62-ce4eecff2d29.png)

Run the code in the master branch by using pnpm dev, and access 127.0.0.1:8080 in browser

**Comment by doodlewind** [comment]
Should be fixed by #1263, please clear the site data and retry. Not sure if this works for #1262.

<img width="762" alt="image" src="https://user-images.githubusercontent.com/7312949/222410616-29b6e113-8916-4cde-98f9-5f8ebf279ecd.png">

Upstream: https://github.com/toeverything/blocksuite/pull/1452

**Comment by Zheaoli** [comment]
This issue still exists. I have recorded a video to help you guys find the root cause.

https://user-images.githubusercontent.com/7054676/222457109-390f28a1-b181-4ef5-87c8-7084f7d2b86b.mov
