### ISSUE TITLE
[Bug]: Android app can't connect to self-hosted server

### ISSUE THREAD

**Issue by anasemam** [toeverything/AFFiNE#13438]
### What happened?

I'm self-hosting the AFFiNE server on my home server using docker compose, it's working just fine and I can access it on my laptop from the desktop app, but when I go to the android app that is available on the play store and paste the same URL that I'm sure is working, it tells me "Unable to connect to server", I quadruple checked the URL, I reinstalled the app, I checked the internet to make sure I'm on the same network, and I double checked to make sure I was pasting in the right field, and I was, but it's still not working. 

### Distribution version

macOS x64 (Intel)

### App Version

_Latest_

### Are you self-hosting?

- [x] Yes

### Self-hosting Version

_Latest_

### Relevant log output

```shell

```

**Comment by brhahlen** [comment]
I'm experiencing this exact same issue

**Comment by jessevl** [comment]
Same issue; Suspect this still has to do with lack selfhosting without ssl (locally)?

**Comment by jessevl** [comment]
Fixed in latest stable (0.24.1) for me.

**Comment by brhahlen** [comment]
I'm running 0.24.1 as well, but I still have the "cannot connect issue"

**Comment by tealtxgr** [comment]
Hey all, I want to share what fixed it for me in case it's useful for others. My reverse proxy, Bunkerweb, had Use CORS enabled for this service. I turned it off and was able to access it. 

Sadly, someone smarter than me will have to explain why this issue is related to headers, as me and HTTP headers aren't the best of friends 😂 Hope this helps others/the developers

**Comment by brhahlen** [comment]
> Hey all, I want to share what fixed it for me in case it's useful for others. My reverse proxy, Bunkerweb, had Use CORS enabled for this service. I turned it off and was able to access it.
> 
> Sadly, someone smarter than me will have to explain why this issue is related to headers, as me and HTTP headers aren't the best of friends 😂 Hope this helps others/the developers

Just got around to testing this now, and this indeed fixes that bit!
I use Traefik and my "Secure Headers" middleware has a comment saying "I don't really understand this, need this" 🤣 

...now I'm stuck on signing in with OIDC 😂

**Comment by futurehome** [comment]
> I'm running 0.24.1 as well, but I still have the "cannot connect issue"

Same for me.

**Comment by steveoriol** [comment]
I have the same problem with the stable version **0.25.7**. 
If I connect with the browser, everything works fine. 
If I use the stable version of the .appimage application, it also works.
But as soon as I try to connect with the Android mobile app, (Android app version : 0.25.7-beta.0)
I get the message “**Unable to connect to the server.**”

**Comment by gpapp** [comment]
@steveoriol 
I managed to connect to my self-hosted instance from Android only when:
* Connection was through SSL 
* all CORS is disabled on my proxy
* I used password auth only - oauth redirect page seems not to be accepted by the Android client as a successful response
* I specified the HTTPS port in the URL - this is a weird requirement but found it on some comment, that you need it

**Comment by steveoriol** [comment]
Thank you @gpapp , but unfortunately, it still does not work for me.
If I ask "curl -I https://affine.netxtime.com", I get :
```
HTTP/2 200 
accept-ranges: bytes
access-control-allow-origin: *
cache-control: public, max-age=0
content-type: text/html; charset=utf-8
date: Tue, 27 Jan 2026 14:19:49 GMT
etag: W/"ae7-19b0106c6e0"
last-modified: Tue, 09 Dec 2025 02:53:00 GMT
permissions-policy: camera 'none'; microphone 'none'; geolocation 'none'; payment 'none';
referrer-policy: same-origin
server-timing: affine-server;dur=2.453027
strict-transport-security: max-age=315360000; includeSubDomains; preload
vary: Origin
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-powered-by: Express
x-request-id: selfhosted:http:835c2931-4755-4e38-93db-832bd97acb83
x-xss-protection: 1; mode=block
content-length: 2791
``` 
Do you have the same thing on your side?

**Comment by steveoriol** [comment]
OK, if I remove the headers.yml of the traefik affine configuration, I get only :
```
url -I https://affine.netxtime.com
HTTP/2 200 
accept-ranges: bytes
access-control-allow-origin: *
cache-control: public, max-age=0
content-type: text/html; charset=utf-8
date: Tue, 27 Jan 2026 14:33:51 GMT
etag: W/"ae7-19b0106c6e0"
last-modified: Tue, 09 Dec 2025 02:53:00 GMT
server-timing: affine-server;dur=3.008419
x-powered-by: Express
x-request-id: selfhosted:http:b73e49da-f32e-4b82-b7f5-b297817eb742
content-length: 2791
```
And now, I pass the first step of the URL in the Android application!
But then I get stuck. When it comes to logging in with my email address.
In fact, after have entered my email address and as soon as I click on “Continue with email”, 
the password field does not appear, and I immediately get an error message “fail to sign in”. :-(
