### ISSUE TITLE
[Bug]: Linked documents on the page are not displayed in the hierarchy when in inline view.

### ISSUE THREAD

**Issue by laidk37** [toeverything/AFFiNE#14081]
### What happened?

Linked documents on the page are not displayed in the hierarchy when in inline view. However, documents are displayed normally in the hierarchy when in card view or embed view.

### Distribution version

Windows x64

### App Version

0.25.7

### Are you self-hosting?

- [x] Yes

### Self-hosting Version

0.25.7

### Relevant log output

```shell

```

### Anything else?

<img width="1382" height="451" alt="Image" src="https://github.com/user-attachments/assets/7eb9e625-fad1-4baa-be25-52dfd1879b9e" />
<img width="1418" height="418" alt="Image" src="https://github.com/user-attachments/assets/4f05b566-2009-4eed-9be0-58f8ce37960b" />

**Comment by uvirra** [comment]
I would like to add on to this issue. I faced the same problem as well, but it only started to happen once I drag a new document from the "All Document" into a document which had sub-documents. Then, the sub-documents are longer displayed and shows "No linked docs".

**Comment by beuster** [comment]
In addition, and possibly related to this, no bidirectional links (backlinks and outgoing links) are displayed at the bottom of the page.

**Comment by KD-MM2** [comment]
Maybe I faced the same problem. Here is the step to reproduce:

### Steps to Reproduce

1. In the **Organize**, create a new folder and name it `1`.
2. Click the `1` 's **+** button to create a new note and name it `a`.
3. Inside note `a`, click the **+** button again to create another note named `b`.  
   - This will create a new note `b` and automatically link it to `a`.  
   - When opening note `a`, note `b` correctly appears as a bi-directional link(`@`) but not correctly showing in **Bi-Directional Links** zone. 
4. However, in the sidebar, when expanding the hierarchy under `a`, it incorrectly shows **No linked docs** instead of displaying the linked note `b`. ← **This is the issue.**

### Version information
- Selfhosted
- Server Version: v0.25.7
- App Version: AFFiNE 0.25.7 Windows x64
- Editor Version: 0.25.7

<img width="1249" height="1001" alt="Image" src="https://github.com/user-attachments/assets/68b6c3ae-03fc-4cc2-97b7-47991736b241" />

### EDIT
There is no problem with the web version, so It may related to the Desktop App.
<img width="1093" height="826" alt="Image" src="https://github.com/user-attachments/assets/a8a2a6ef-a84a-4c8f-b44c-04299e2f870e" />

**Comment by ghdragunoff** [comment]
I have the same problem in the desktop app on macOS

### **Version information**
Selfhosted
Server Version: 0.25.7
App Version: AFFiNE 0.25.7 macOS 15.7.2
Editor Version: 0.25.7

**Comment by bearlikelion** [comment]
I am also having the same issue self hosting!

Web on the left, desktop app on the right:

<img width="1734" height="1649" alt="Image" src="https://github.com/user-attachments/assets/5c60b471-0e18-4f41-abaf-3c29807a57f4" />

# Version information
Self-hosted
Server Version: 0.25.7
App Version: AFFiNE 0.25.7 Arch Linux 
Editor Version: 0.25.7

**Comment by mwhouser** [comment]
I hit this same issue just today. Windows app only, web is fine.

I'm not aware of anything I did to trigger it. I noticed that some docs I rarely touch were missing their children today.

**Comment by ATPs** [comment]
found the same problem.

I downgraded to 0.25.5, and found this bug still there.

**Comment by sp4c38** [comment]
Same issue. Also only on the (Mac) desktop app. In the browser the organization structure renders correctly.

**Edit:** Just downloaded the AFFiNE beta [v0.26.0-beta.0](https://github.com/toeverything/AFFiNE/releases/tag/v0.26.0-beta.0) mac app. Bug if fixed here.

**Comment by darkskygit** [comment]
already fixed in 0.26, stable coming soon

**Comment by mwhouser** [comment]
Just updated self-hosted to 0.26.2 and client to 0.26.2.

Still an issue.

<img width="337" height="264" alt="Image" src="https://github.com/user-attachments/assets/537e6551-c683-41ae-941e-b579506795a4" />

**Comment by darkskygit** [comment]
> Just updated self-hosted to 0.26.2 and client to 0.26.2.
> 
> Still an issue.
> 
> <img alt="Image" width="337" height="264" src="https://private-user-images.githubusercontent.com/1119525/547833384-537e6551-c683-41ae-941e-b579506795a4.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzA3NDkwOTQsIm5iZiI6MTc3MDc0ODc5NCwicGF0aCI6Ii8xMTE5NTI1LzU0NzgzMzM4NC01MzdlNjU1MS1jNjgzLTQxYWUtOTQxZS1iNTc5NTA2Nzk1YTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI2MDIxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNjAyMTBUMTgzOTU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTljNjhmNjVmZDYxMmFlYjYxMjc4MWI0NTlmZmEzYmQxNzdhYTM2NTc4YzdjNDRmMjlhZTI0NDcxY2FlODQzYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.P7P1lozakbIFDrZNhsNkyargcSfi4yEoNOBDVZl3dR4">

<img width="247" height="237" alt="Image" src="https://github.com/user-attachments/assets/6ca6117f-c7fb-4740-acb9-5b90b30ba2c7" />

The doc reference are managed by the indexing service, for performance reasons, the indexing service currently only refreshes the reference record for docs when they are modified.

You can currently trigger related updates by modifying the document, we may provide a forced refresh button or more intelligent refresh logic in the next version.

**Comment by mwhouser** [comment]
Confirmed. After editing the doc, the sub-documents appeared.

Thanks.
