### ISSUE TITLE
​The button is in the wrong spot after resizing the page. 

### ISSUE THREAD

**Issue by rgkirch** [toeverything/AFFiNE#2200]
### What happened?

![image](https://user-images.githubusercontent.com/6143833/235308332-dac2a5cf-3f4e-4a9b-a30f-8f6d7f2460a8.png)
That button on the left is in the wrong spot after zooming in like this.
![image](https://user-images.githubusercontent.com/6143833/235308361-553d1123-b081-4808-bb9d-ece748409580.png)
Or zooming out like this.
![image](https://user-images.githubusercontent.com/6143833/235308374-e053f740-5ff5-4e2c-a13f-55ff82955436.png)

### Version

app.affine.pro

### What browsers are you seeing the problem on?

Chrome

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by lawvs** [comment]
I believe this issue has been resolved in the latest version.

**Comment by rgkirch** [comment]
I'm on pre-alpha and it looks like the general problem still exists.
e.g.
clicking on the three vertical buttons
![image](https://github.com/toeverything/AFFiNE/assets/6143833/a4fb00cb-a306-465b-a22c-77352fb9231d)
and then zooming out
![image](https://github.com/toeverything/AFFiNE/assets/6143833/60c3fc99-a935-45ba-9ffd-44a44fd15c8e)
or zooming in
![image](https://github.com/toeverything/AFFiNE/assets/6143833/bc783679-78ac-46a6-9f9a-0b51cdcc337a)

**Comment by joebeijing** [comment]
> I'm on pre-alpha and it looks like the general problem still exists. e.g. clicking on the three vertical buttons ![image](https://user-images.githubusercontent.com/6143833/243180344-a4fb00cb-a306-465b-a22c-77352fb9231d.png) and then zooming out ![image](https://user-images.githubusercontent.com/6143833/243180365-60c3fc99-a935-45ba-9ffd-44a44fd15c8e.png) or zooming in ![image](https://user-images.githubusercontent.com/6143833/243180374-bc783679-78ac-46a6-9f9a-0b51cdcc337a.png)

The pre-alpha version is already in maintenance mode. I recommend downloading and using the latest version. https://affine.pro/download

**Comment by rgkirch** [comment]
Ok, sorry. I was confused as to whether `latest` or `pre-alpha` was the actual latest.
![image](https://github.com/toeverything/AFFiNE/assets/6143833/fe6eb439-c462-49f3-827d-cccef59f296a)
It says that both were published 4 months ago. I was on `latest` but it the app didn't look like it was updated after running `docker pull`. What can I use to get the latest docker? Or is it now just a client program like what you linked to?
Thank you!

**Comment by joebeijing** [comment]
Apologize for the inconvenience. The update progress for Docker is currently behind schedule and is being worked on. We kindly ask for your patience while we complete this process. You can track the progress by clicking on this issue.
https://github.com/toeverything/OctoBase/issues/457

**Comment by rgkirch** [comment]
That's helpful; thank you so much for the response!
