### ISSUE TITLE
Can not import files on Firefox [bug]: 

### ISSUE THREAD

**Issue by notaprodev** [toeverything/AFFiNE#454]
### Describe the bug

I am unble to import exported files when using Firefox

### To Reproduce

1. Go to the demo or your instance affine on Firefox
2. Export a file
3. try to import the file nothing happens

### Screenshots

![Screenshot from 2022-09-22 10-11-50](https://user-images.githubusercontent.com/64326282/191693905-323247bd-a598-4a2a-9dec-3e3411a7f0b3.png)

### Expected behavior

to open a windows that allows to import a file

### Platform

Linux

### Browser

Firefox

**Comment by CJSS** [comment]
Hi there,

This was fixed (you can refer to #449).

Though you will likely need to pull the latest Docker and/or clear your browser cache for the app to be updated.

Thank you.

**Comment by CJSS** [comment]
As I have not received a response, and this should be resolved (should be just a cache issue). I'll move forward and close this ticket.

If you still have issues please reach out to us.

**Comment by notaprodev** [comment]
Apologies for the late response. Unfortunately, the issue is still present of Firefox 104 on Ubuntu 20.04

**Comment by shoriwe** [comment]
Hello, this issue is still present.

```
TypeError: window.showOpenFilePicker is not a function
    load http://localhost:4200/main.7169101b.js:139
    onClick http://localhost:4200/main.7169101b.js:3
    onClick http://localhost:4200/main.7169101b.js:3
    onClick http://localhost:4200/main.7169101b.js:3
    ze http://localhost:4200/ui.ba1dfdd9.js:102
    $e http://localhost:4200/ui.ba1dfdd9.js:102
    Ar http://localhost:4200/ui.ba1dfdd9.js:102
    Ar http://localhost:4200/ui.ba1dfdd9.js:102
    Lr http://localhost:4200/ui.ba1dfdd9.js:102
    Vr http://localhost:4200/ui.ba1dfdd9.js:102
    uu http://localhost:4200/ui.ba1dfdd9.js:102
    De http://localhost:4200/ui.ba1dfdd9.js:102
    Vr http://localhost:4200/ui.ba1dfdd9.js:102
    Kt http://localhost:4200/ui.ba1dfdd9.js:102
    Ht http://localhost:4200/ui.ba1dfdd9.js:102
```
