### ISSUE TITLE
Pages in local workspace before September cannot be opened

### ISSUE THREAD

**Issue by YanxinLu0122** [toeverything/AFFiNE#4927]
https://github.com/toeverything/AFFiNE/assets/144991896/ba9604f5-91df-4a65-815d-a8cb7cda9837

**Comment by YanxinLu0122** [comment]
some of the workspace still exist:

![Image](https://github.com/toeverything/AFFiNE/assets/144991896/a3aeaafd-6573-4345-8bc7-cb16ecc31a11)
![Image](https://github.com/toeverything/AFFiNE/assets/144991896/df99029a-be34-4063-bf95-56ea883b6a22)
![Image](https://github.com/toeverything/AFFiNE/assets/144991896/bcc6c608-a1f5-4ef3-bd82-d1b2872b5ab8)

**Comment by EYHN** [comment]
should fixed by 0.10.2

**Comment by YanxinLu0122** [comment]
still exist

![Image](https://github.com/toeverything/AFFiNE/assets/144991896/63bdd322-e0b3-42e4-9e58-5d68f33ab0fb)

**Comment by lawvs** [comment]
Related to https://github.com/toeverything/AFFiNE/issues/4875 https://github.com/toeverything/AFFiNE/issues/5029

**Comment by YanxinLu0122** [comment]
still exist

https://github.com/toeverything/AFFiNE/assets/144991896/9bb26e7f-893e-435b-994b-2e026e62cac9

**Comment by joooye34** [comment]
The data of this case is actually empty, maybe the data is corrupted when migration!
