### ISSUE TITLE
Pages vanish​

### ISSUE THREAD

**Issue by AnetteMM** [toeverything/AFFiNE#5370]
### What happened?

Since I installed and use the current portable version, new pages do not get saved or are not displayed.

App Version
0.10.3
Editor Version
0.0.0-20231122113751-6bf81eb3-nightly

### Distribution version

Windows x64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by JimmFly** [comment]
thank you for opening this issue and contributing to AFFiNE. We have fixed this issue in the latest version. You can export an existing workspace and back it up before attempting to upgrade. Your issue should be resolved after upgrading.

I will keep updating this question as it progresses. If you or others find anything else or have any additional information about this issue, please feel free to share it here.

**Comment by AnetteMM** [comment]
Thank you for answering. I downloaded and installed the newest version and the problem persists. Now the page is saved, but as an empty page.

**Comment by JimmFly** [comment]
I'm terribly sorry, but would you be able to provide a written reproduction process or, alternatively, upload a video recording? This way, we can gain a better understanding of the issue at hand.

**Comment by AnetteMM** [comment]
Thank You!!!
