### ISSUE TITLE
Self-hosted: add config for turn off signup feature

### ISSUE THREAD

**Issue by chief-nerd** [toeverything/AFFiNE#6141]
### What happened?

Wanted to host a test version and close down the signup so users are not accidently signing up to my "private" test system.

Installed Docker Image with supplied docker-compose. Setup all great and easy.
Now I tried to deactivate Signups.

1st bug:
Found an existing ENV and set `OAUTH_GOOGLE_ENABLED=false` --> but that is not working. Button is still displayed.

2nd bug:
Email signup. No direct ENV. After digging I found in `dist/fundamentals/config/default.js` -> `defaultConfig` a flag in `auth.enableSignup` --> BINGO!

---
Now I wanted to set it:
1st try: in my mapped config folder (corresponds to `/root/.affine/config`) in `affine.js` I added:
```
AFFiNE.auth.enableSignup = false;
AFFiNE.auth.enableOauth = false;
```
without effect. :(

---
Then I tried another "hacky" way
I edited `affine.env.js` and added based on the logic of the Google / Github variables there:
```
SIGNUP_ENABLED: ['auth.enableSignup', 'boolean'],`
```
and in my otherwise working `.env` file:
```
OAUTH_GOOGLE_ENABLED=false
SIGNUP_ENABLED=false
```
... also not working :(

---
So I report this as a "bug" since the functionality seems to be there, but is NOT working.

### Distribution version

Web (app.affine.pro)

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Are you self-hosting?

- [X] Yes

**Comment by darkskygit** [comment]
we have refactoring related components in the last two major versions, and the corresponding env var are outdated.

please go to our docs to view the latest available env vars: https://docs.affine.pro/docs/self-host-affine/run-affine-with-custom-options

specifically, in the latest version, as long as the OAUTH_* env are not defined, the oauth feature will be turned off, but there is currently no config item that can turn off the registration feature.

i have recorded the config item of turn off the registration feature in the development schedule, once there are relevant updates, i will associate it with this issue.

**Comment by chief-nerd** [comment]
Why the close? I thought this was planned?

**Comment by forehalo** [comment]
done already actually. wait for the release of 0.15

**Comment by alissa-tung** [comment]
Hello, do we already have this feature? I am trying to disable user sign up, and just allow admin to send email. Can we make this reachable?

**Comment by samwh1te** [comment]
I've just pulled 0.15.7 and it seems this issue still exists?

**Comment by Braintelligence** [comment]
I'm on 0.16, did you add the possibility of closed signup or invite-only signup? I can't find anything about this in the custom options.

**Comment by darkskygit** [comment]
> I'm on 0.16, did you add the possibility of closed signup or invite-only signup? I can't find anything about this in the custom options.

goto /admin/settings and turn of "Whether allow new registrations"

**Comment by Bottleface** [comment]
> > I'm on 0.16, did you add the possibility of closed signup or invite-only signup? I can't find anything about this in the custom options.
> 
> goto /admin/settings and turn of "Whether allow new registrations"

I've been seeing comments across issues and the forums mention this admin panel but had no idea how to get to it, THANK YOU!

**Comment by smileBeda** [comment]
<img width="1883" height="744" alt="Image" src="https://github.com/user-attachments/assets/4e57310c-4212-40d1-86dd-9aa3ec8f6b4b" />

> I'm on 0.16, did you add the possibility of closed signup or invite-only signup? I can't find anything about this in the custom options.
> goto /admin/settings and turn of "Whether allow new registrations"

It does unfortunately not work
I disabled it, and yet, the Public sign up form is still there, and still states `To continue signing in, please enter the code that was sent to xxxxxx.` after submitting the form with an email.

I think it wouldn't send the mail as per error log console, but, the UI does not actually do what it should (_disable signup_)
