### ISSUE TITLE
​After upgrading to 0.16.2, the code box is completely messed up

### ISSUE THREAD

**Issue by MortalAndTry** [toeverything/AFFiNE#7861]
### What happened?

![image](https://github.com/user-attachments/assets/1c4db8c8-f059-4e62-81a2-825cb6c50845)

### Distribution version

Windows x64

### Are you self-hosting?

- [ ] Yes

**Comment by MortalAndTry** [comment]
![image](https://github.com/user-attachments/assets/9b5b747c-8b16-42cd-a4f8-9a2a51d7f64c)
god!

**Comment by Yinmlmaoliang** [comment]
​After upgrading to 0.16.2, the same issue occurred with self-hosting. I used Microsoft or Google browsers to open the application interface, and when I tried to copy the code from VSCode into the code block, the following situation occurred:
<img width="449" alt="屏幕截图 2024-08-14 110745" src="https://github.com/user-attachments/assets/27769e7e-27a9-447b-91f1-01fd07c99e52">
Similarly, when I use the 'enter' key, I cannot successfully create a new code line in the code block.
<img width="461" alt="屏幕截图 2024-08-14 103630" src="https://github.com/user-attachments/assets/01545c57-d6b6-43f8-85e6-9c472325366c">

**Comment by forehalo** [comment]
lol, we missed a blocksuite fix in the latest version. will patch it soon

**Comment by forehalo** [comment]
fixed in 0.16.3

**Comment by raushanraja** [comment]
I am still having the same issue. I see the version in about is 0.16.3 (self hosted)


![2024-08-15-023752_1598x339_scrot](https://github.com/user-attachments/assets/dcba31fb-dbdd-4bdd-b729-45cf0d3a8e94)



![2024-08-15-023723_877x372_scrot](https://github.com/user-attachments/assets/827e8f67-c812-47a7-983e-f51e8e5795d6)
