### ISSUE TITLE
Unable to change Google account after first time logged in

### ISSUE THREAD

**Issue by doodlewind** [toeverything/AFFiNE#795]

**Comment by tzhangchi** [comment]
@darkskygit it's config problem about firebase?

**Comment by tzhangchi** [comment]
> > @darkskygit it's config problem about firebase?
> 
> 
> 
> logout logic is not handled correctly

@darkskygit as a result，who would be responsible for it？

**Comment by darkskygit** [comment]
> > > @darkskygit it's config problem about firebase?
> > 
> > 
> > logout logic is not handled correctly
> 
> @darkskygit as a result，who would be responsible for it？

@DiamondThree https://firebase.google.com/docs/reference/js/auth.auth.md?hl=zh-cn#authsignout

**Comment by pengx17** [comment]
fixed by https://github.com/toeverything/AFFiNE/pull/936

**Comment by joebeijing** [comment]
I can still reproduce this issue when I log out and try to login again in

**Comment by pengx17** [comment]
> I can still reproduce this issue when I log out and try to login again in

I noticed the same issue as well, but it does not happen all the time. Seems to be an issue on the firebase/google side

**Comment by joebeijing** [comment]
@pengx17 I can reproduce this issue when I first log out and log in again, then it back to normal.
